default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: <%= ENV.fetch("POSTGRES_DB") { "photo-review-6" } %>
  # username: <%= ENV.fetch("POSTGRES_USER") { "photo-review-6" } %>
  # password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  # host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "photo-review-6" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "photo-review-6" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "photo-review-6" } %>_production
